"""Added time expiration in calendarshare

Revision ID: 3867f62e9fb8
Revises: c7a83839cb94
Create Date: 2024-02-29 10:34:33.400069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3867f62e9fb8'
down_revision = 'c7a83839cb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendarshares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendarshares', schema=None) as batch_op:
        batch_op.drop_column('expiration_time')

    # ### end Alembic commands ###
